spring.application.name=mobile-shop


spring.data.mongodb.uri=mongodb+srv://randiranirman20011210_db_user:rPsjeWCoW0YXhQzT@cluster0.ceqnuqf.mongodb.net/mobile-shop


springdoc.swagger-ui.path=swagger-ui.html

